//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 03/06/2024 11:36:02
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"MidiGlass"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"MidiGlass (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"MidiGlass (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"MidiGlass"
#define PROGRAM_REGKEY  L"Macallan\\MidiGlass"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\MidiGlass"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "MidiGlass"
#ifdef _WIN64
#define PROGRAM_NAME_P  "MidiGlass (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "MidiGlass (x86 MBCS)"
#endif
#define PROGRAM_SECT    "MidiGlass"
#define PROGRAM_REGKEY  "Macallan\\MidiGlass"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\MidiGlass"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Mon Jun 03 11:36"
#define PROGRAM_DATE_F  L"Mon Jun 03 11:36 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/06/03 11:36:02"
#else
#define PROGRAM_DATE    "Mon Jun 03 11:36"
#define PROGRAM_DATE_F  "Mon Jun 03 11:36 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/06/03 11:36:02"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"4.0.03.005"
#define PROGRAM_INSTALL L"4.0.03005"
#define PROGRAM_VER_NUM 40003005
#define PROGRAM_BUILD   L"189"
#define PROGRAM_TITLE   L"Midi Glass"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"Midi Glass (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"Midi Glass (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "4.0.03.005"
#define PROGRAM_INSTALL "4.0.03005"
#define PROGRAM_VER_NUM 40003005
#define PROGRAM_BUILD   "189"
#define PROGRAM_TITLE   "Midi Glass"
#ifdef _WIN64
#define PROGRAM_TITLE_P "Midi Glass (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "Midi Glass (x86 MBCS)"
#endif
#endif

#endif

