//{{NO_DEPENDENCIES}}
// Fichier Include généré de Microsoft Visual C++.
// Utilisé par MidiGlass.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_ERROR              104
#define ID_STAFF_SCROLLBAR              105
#define ID_TOOLS_TOOL9                  106
#define ID_TOOLS_TOOL10                 107
#define ID_TOOLS_TOOL11                 108
#define ID_TOOLS_TOOL12                 109
#define ID_TOOLS_TOOL13                 110
#define ID_TOOLS_TOOL14                 111
#define ID_TOOLS_TOOL15                 112
#define ID_TOOLS_TOOL16                 113
#define ID_TOOLS_TOOL17                 114
#define ID_TOOLS_TOOL18                 115
#define ID_TOOLS_TOOL19                 116
#define ID_TOOLS_TOOL20                 117
#define IDR_IE_LARGE_TOOLBAR            118
#define IDR_MIDI_LARGE_TOOLBAR          119
#define IDR_MCI_LARGE_TOOLBAR           120
#define IDR_LARGE_MAINFRAME_TOOLBAR     121
#define IDR_LARGE_MAINFRAME             122
#define IDR_EXPLORER_VIEW               123
#define IDR_TRACK_VIEW                  124
#define IDC_SOUNDFONT_COMBO_1           125
#define IDR_SF2_LARGE_TOOLBAR           127
#define IDR_MAINFRAME                   128
#define IDC_SOUNDFONT_COMBO_2           128
#define IDR_MIDITYPE                    129
#define ID_EVENTS_INSERT_SEQUENCE       129
#define ID_EVENTS_INSERT_TEXT           130
#define IDD_GENERAL_VIEW                131
#define ID_EVENTS_INSERT_COPYRIGHT      132
#define ID_EVENTS_INSERT_TRACKNAME      133
#define ID_EVENTS_INSERT_INSTRNAME      134
#define IDD_TRACKS_VIEW                 135
#define IDD_TEXT_VIEW                   136
#define IDD_TRACK_EVENTS                137
#define IDD_EVENT_DETAIL                138
#define ID_EVENTS_INSERT_LYRICS         139
#define ID_EVENTS_INSERT_MARKERS        140
#define IDR_MENU_TRACKS                 141
#define IDR_MENU_EVENTS                 142
#define ID_EVENTS_INSERT_CUEPOINT       143
#define ID_EVENTS_INSERT_SEQUENCER      144
#define ID_EVENTS_INSERT_SYSEX          145
#define ID_EVENTS_INSERT_STARTTRACK     146
#define ID_EVENTS_INSERT_STARTTRACK20   147
#define ID_EVENTS_INSERT_ENDOFTRACK     148
#define IDD_MIDI_PLAYER                 149
#define IDB_PLAY                        150
#define IDB_PAUSE                       151
#define IDB_STOP                        152
#define IDB_FORWARD                     153
#define IDB_BACKWARD                    154
#define IDB_LOOP                        155
#define IDR_MCI_TOOLBAR                 156
#define IDR_MIDI_TOOLBAR                158
#define IDD_CORRECT_OPTION              160
#define IDD_ERRORTEXT                   163
#define IDD_PREFERENCES                 164
#define IDD_CONTROLER                   166
#define IDD_PLAYLIST                    167
#define IDD_PLAY_THREAD                 168
#define IDB_BACKGROUND                  169
#define IDB_BACK_EMPTY                  170
#define IDB_IMAGE_16X2                  171
#define IDB_IMAGE_32X2                  172
#define IDB_IMAGE_48X2                  173
#define IDR_MENU_PLAYLIST               175
#define IDD_PLAYLIST_PROPERTY           176
#define IDB_MCI_TOOLBAR                 177
#define IDB_MIDI_TOOLBAR                178
#define IDB_MAINFRAME                   179
#define IDB_ABOUT_PICTURE               180
#define IDB_EVENT_ICONS                 181
#define IDB_EVENT_ICONS32               182
#define IDR_TOOL                        183
#define IDD_TRACK_DETAIL                184
#define IDD_CHANNELS                    185
#define IDR_MENU_CHANNELS               186
#define IDR_IE_TOOLBAR                  187
#define IDR_MENU_VIEWS                  189
#define IDB_CHANNEL_STATE               191
#define IDR_MENU_STAFF                  193
#define IDR_MIDIFILE1                   195
#define IDD_NOTES_VIEW                  196
#define IDR_MIDIRTF1                    197
#define IDB_EXPLORER_ICONS              198
#define IDR_MENU_EXPLORER               199
#define IDD_PLAYDIR_THREAD              200
#define IDD_MODIFY_THREAD               201
#define IDD_PLAYER_DIALOG               202
#define IDB_FORW                        203
#define IDB_BACK                        204
#define IDD_FIND_EVENT                  205
#define IDD_SYSEX                       206
#define IDD_RECORD_DIALOG               208
#define IDC_POINT_TO                    210
#define IDI_MIDI1                       211
#define IDI_MIDI2                       212
#define IDI_ICON2                       213
#define IDI_MIDI3                       213
#define IDR_SF2_TOOLBAR                 214
#define ID_EVENTS_INSERT_SETTEMPO       215
#define ID_EVENTS_INSERT_SETSMPTE       216
#define ID_EVENTS_INSERT_TIMESIG        217
#define ID_EVENTS_INSERT_KEYSIG         218
#define ID_EVENTS_INSERT_NOTEOFF        219
#define ID_EVENTS_INSERT_NOTEON         220
#define ID_EVENTS_INSERT_KEYPRESSURE    221
#define ID_EVENTS_INSERT_PARAMETER      222
#define ID_EVENTS_INSERT_PROGRAM        223
#define ID_EVENTS_INSERT_CHANNELPRES    224
#define ID_EVENTS_INSERT_WHEEL          225
#define IDR_MENU_EMPTY                  226
#define IDD_MWFORMVIEW                  227
#define IDR_MIDIFILE2                   227
#define IDC_EVENTNAME                   1001
#define IDC_TRACKS_LIST                 1002
#define IDC_TRACK_EVENT_LIST            1003
#define IDC_PREVIOUS                    1004
#define IDC_NEXT                        1005
#define IDC_DELTA_TIME                  1005
#define IDC_START                       1006
#define IDC_REFRESH                     1007
#define IDC_MESURE                      1007
#define IDC_FORMAT                      1008
#define IDC_EVENT_EXTRA_TEXT            1008
#define IDC_NBTRACKS                    1009
#define IDC_MESSAGE                     1009
#define IDC_DIVISION_HI                 1010
#define IDC_EVENT_COMBO                 1010
#define IDC_DIVISION_LO                 1011
#define IDC_PLAY                        1011
#define IDC_EVENT_COMBO_1               1011
#define IDC_TEXT                        1012
#define IDC_TIME                        1012
#define IDC_EVENT_VALUE_1               1012
#define IDC_STOP                        1013
#define IDC_EVENT_VALUE_2               1013
#define IDC_PROGRESS                    1014
#define IDC_EVENT_VALUE_3               1014
#define IDC_PAUSE                       1015
#define IDC_EVENT_VALUE_4               1015
#define IDC_FORWARD                     1016
#define IDC_EVENT_VALUE_5               1016
#define IDC_BACKWARD                    1017
#define IDC_MAXIMUM                     1018
#define IDC_STATE                       1019
#define IDC_SLIDER                      1020
#define IDC_SLIDER_SPEED                1021
#define IDC_TRACKNAME                   1022
#define IDC_BACK                        1022
#define IDC_ADDENDTRACK                 1023
#define IDC_FORW                        1023
#define IDC_ADDSTARTTRACK               1027
#define IDC_FILTER                      1028
#define IDC_BANKSELECTHIGH              1029
#define IDC_BANKSELECTLOW               1030
#define IDC_CORRECT_STARTOFTRACK        1031
#define IDC_SYSEX                       1032
#define IDC_ERROR_MESSAGE               1033
#define IDC_START_PLAYING               1035
#define IDC_CONTROLER                   1036
#define IDC_SETTINGS                    1037
#define IDC_CHECK_SETTINGS              1038
#define IDC_SKIP_TO_NOTE                1039
#define IDC_ADD                         1041
#define IDC_REMOVE                      1042
#define IDC_TUNE                        1042
#define IDC_SAVE                        1043
#define IDC_NUMBER                      1044
#define IDC_DOWN                        1045
#define IDC_UP                          1046
#define IDC_PLAYLIST                    1047
#define IDC_DISPLAY                     1049
#define IDC_FILENAME                    1050
#define IDC_DEVICES                     1051
#define IDC_ARRANGE                     1052
#define IDC_IN_DEVICES                  1052
#define IDC_TRACK_NUMBER                1054
#define IDC_TRACK_SIZE                  1055
#define IDC_CHANNELS                    1055
#define IDC_SPIN2                       1059
#define IDC_EDIT_COLUMNS                1060
#define IDC_LEGAL_COPYRIGHT             1060
#define IDC_EDIT_COLUMNS_SPIN           1061
#define IDC_LEGAL_TRADEMARK             1061
#define IDC_COMMENTS                    1062
#define IDC_PRODUCT_NAME                1063
#define IDC_PRODUCT_VERSION             1064
#define IDC_INTERNAL_NAME               1066
#define IDC_PLAY_TUNE                   1067
#define IDC_RICHEDIT_TEXT               1069
#define IDC_SPIN                        1070
#define IDC_SPIN_NUMBER                 1071
#define IDC_TUNE_COMBO                  1072
#define IDC_SPIN_EVENT                  1074
#define IDC_COMPACT                     1075
#define IDC_LARGE_BAR                   1076
#define IDC_REBAR                       1077
#define IDC_PROGRAM_COMBO               1079
#define IDC_CONTROLLER_COMBO            1080
#define IDC_V1_FROM                     1081
#define IDC_SPIN_V1_FROM                1082
#define IDC_V1_TO                       1083
#define IDC_BACKGROUND                  1083
#define IDC_SPIN_V1_TO                  1084
#define IDC_CONTROL_COLOR               1084
#define IDC_V2_FROM                     1085
#define IDC_SPLITTER                    1085
#define IDC_SPIN_V2_FROM                1086
#define IDC_SPLITTER2                   1086
#define IDC_USE_SF                      1086
#define IDC_V2_TO                       1087
#define IDC_SPIN_V2_TO                  1088
#define IDC_SYSEX_VALUES                1088
#define IDC_DEFAULT                     1089
#define IDC_WEB                         1090
#define IDC_EMAIL                       1091
#define IDC_MIDIFILE                    1091
#define IDC_WAVE_DIRECTORY              1092
#define IDC_SOUND_FONT_FILE             1093
#define IDC_PROGRESS_BAR                1094
#define IDC_START_RECEIVE               1096
#define IDC_STOP_RECEIVE                1097
#define IDC_SIZE_RECEIVE                1098
#define IDC_CHECK_RECEIVE               1099
#define IDC_MAIL                        1099
#define ID_BROWSE                       1100
#define IDC_ERROR_HEADER                1101
#define IDC_EVENT_LABEL_1               1102
#define IDC_EVENT_TEXT_1                1103
#define IDC_EVENT_CHANNEL               1104
#define IDC_EVENT_TEXT_2                1105
#define IDC_EVENT_TEXT_3                1106
#define IDC_EVENT_TEXT_4                1107
#define IDC_EVENT_TEXT_5                1108
#define IDC_NUM_LABEL_1                 1109
#define IDC_NUM_TEXT_1                  1110
#define IDC_NUM_TEXT_2                  1111
#define IDC_NUM_TEXT_3                  1112
#define IDC_NUM_TEXT_4                  1113
#define IDC_NUM_TEXT_5                  1114
#define ID_CONTENT_HEADER               32782
#define ID_CONTENT_TRACKS               32783
#define ID_CONTENT_EVENTS_SEQUENCE      32785
#define ID_CONTENT_EVENTS_TEXT          32786
#define ID_CONTENT_EVENTS_COPYRIGHT     32787
#define ID_CONTENT_EVENTS_TRACKNAME     32788
#define ID_CONTENT_EVENTS_INSTRUMENTNAME 32789
#define ID_CONTENT_EVENTS_LYRICS        32790
#define ID_CONTENT_EVENTS_MARKERS       32791
#define ID_CONTENT_EVENTS_CUEPOINT      32792
#define ID_CONTENT_EVENTS_SEQUENCER     32793
#define ID_CONTENT_SYSTEMEXCLUSIVE      32794
#define ID_FILE_PLAYMIDI                32795
#define ID_FILE_TRACE                   32796
#define ID_CORRECT_STARTOFTRACK         32797
#define ID_CORRECT_ENDOFTRACK           32798
#define ID_TRACKS_PROPERTY              32800
#define ID_TRACKS_DELETE                32801
#define ID_EVENTS_DETAIL                32802
#define ID_EVENTS_DELETE                32803
#define ID_EVENTS_MODIFY                32805
#define ID_EVENTS_HELP                  32806
#define ID_TRACKS_HELP                  32807
#define ID_FILE_SEQUENCER_PLAY          32812
#define ID_FILE_SEQUENCER_PAUSE         32813
#define ID_FILE_SEQUENCER_STOP          32814
#define ID_FILE_SEQUENCER_RESUME        32815
#define ID_FILE_MEDIAPLAYER             32818
#define ID_FILE_SEQUENCER_PLAYANDLOOP   32819
#define ID_FILE_SEQUENCER_PLAYLL        32826
#define ID_FILE_SEQUENCER_STOPLL        32827
#define ID_CONTENT_PLAYER               32830
#define ID_SEQUENCE_PAUSE               32831
#define ID_FILE_SEQUENCER_RESUMELL      32839
#define ID_FILE_SEQUENCER_PAUSELL       32843
#define ID_FILE_SEQUENCER_PLAYANDLOOPLL 32844
#define ID_FILE_SEQUENCER_BACKWARDLL    32845
#define ID_FILE_SEQUENCER_FORWARDLL     32846
#define ID_VIEW_MCITOOLBAR              32851
#define ID_VIEW_MIDITOOLBAR             32858
#define ID_VIEW_ARRANGETOOLBARS         32859
#define ID_CORRECT_FILTERTRACKS         32860
#define ID_CORRECT_ADD_GMRESET          32861
#define ID_CORRECT_ADD_GSRESET          32862
#define ID_CORRECT_ALL                  32863
#define ID_CORRECT_REMOVE_SYSTEMEXCLUSIVE 32864
#define ID_REMOVE_SYSTEMEXCLUSIVE       32864
#define ID_CORRECT_REMOVE_CONTROLLERBANKSELECT 32865
#define ID_CORRECT_OPTIONS              32866
#define ID_CONTENT_ERRORMESSAGES        32867
#define ID_FILE_PREFERENCES             32868
#define ID_CONTENT_PARAMETERS           32869
#define ID_REMOVE_CONTROLLER_BANKSELECTHIGH 32870
#define ID_REMOVE_CONTROLLER_BANKSELECTLOW 32871
#define ID_REMOVE_SEQUENCE              32875
#define ID_REMOVE_TEXT                  32876
#define ID_REMOVE_COPYRIGHT             32877
#define ID_REMOVE_TRACKNAME             32878
#define ID_REMOVE_INSTRUMENTNAME        32879
#define ID_REMOVE_LYRICS                32880
#define ID_REMOVE_MARKERS               32881
#define ID_REMOVE_CUEPOINT              32882
#define ID_REMOVE_SEQUENCER             32883
#define ID_CONTENT_PLAYLIST             32884
#define ID_FILE_ADDTOTHEPLAYLIST        32885
#define ID_PLAYLIST_OPENFILE            32886
#define ID_PLAYLIST_HELP                32887
#define ID_PLAYLIST_PROPERTY            32888
#define ID_VIEW_MAINTOOLBAR             32889
#define ID_CORRECT_TIMESIGNATURE        32891
#define ID_CORRECT_KEYSIGNATURE         32892
#define ID_CORRECT_MOVE_ALL             32893
#define ID_LARGEICONS                   32898
#define ID_SMALLICONS                   32899
#define ID_LIST                         32900
#define ID_REPORT                       32901
#define ID_ARRANGE                      32903
#define ID_TOOLS_TOOL1                  32904
#define ID_TOOLS_TOOL2                  32905
#define ID_TOOLS_TOOL3                  32906
#define ID_TOOLS_TOOL4                  32907
#define ID_TOOLS_TOOL5                  32908
#define ID_TOOLS_TOOL6                  32909
#define ID_TOOLS_TOOL7                  32910
#define ID_TOOLS_TOOL8                  32911
#define ID_TOOLS_EXPLORER               32912
#define ID_TRACKS_PLAYSOLO              32913
#define ID_TRACKS_MUTE                  32914
#define ID_TRACKS_AUDIBLE               32915
#define ID_CONTENT_CHANNELS             32916
#define ID_CHANNELS_HELP                32917
#define ID_CHANNELS_MUTE                32918
#define ID_CHANNELS_AUDIBLE             32919
#define ID_CHANNELS_MUTEALL             32920
#define ID_CHANNELS_AUDIBLEALL          32921
#define ID_TRACKS_MUTEALL               32922
#define ID_TRACKS_AUDIBLEALL            32923
#define ID_CHANNELS_SOLO                32924
#define ID_VIEW_TWOVIEWS                32925
#define ID_VIEW_LEFTVIEW                32926
#define ID_VIEW_RIGHTVIEW               32927
#define ID_REMOVE_RESETALLCONTROLERS    32928
#define ID_HOMEPAGE_URL                 32930
#define ID_CONTENT_START_IE             32934
#define ID_CONTENT_STOP_IE              32935
#define ID_VIEW_IETOOLBAR               32936
#define ID_CONTENT_STAFF                32939
#define ID_STAFF_HELP                   32941
#define ID_CORRECT_TRUNCATE_NOTE        32942
#define ID_STAFF_SCALE                  32943
#define ID_CONTENT_NOTES                32944
#define ID_CONTENT_MIDIEXPLORER         32945
#define ID_CONTENT_TRACKS_LIST          32947
#define ID_EXPLORER_HELP                32948
#define ID_EXPLORER_RENAME              32949
#define ID_EXPLORER_DELETE              32950
#define ID_EXPLORER_OPEN                32951
#define ID_EXPLORER_PLAYDIR             32952
#define ID_EXPLORER_MODIFYFILES         32953
#define ID_EXPLORER_REFRESH             32954
#define ID_EDIT_FINDAGAIN               32956
#define ID_CORRECT_ADD_XGRESET          32957
#define ID_FILE_SAVEGEOMETRY            32958
#define ID_CONTENT_EVENTS_SHOWHIDE      32959
#define ID_FILE_RECORD                  32960
#define ID_EXPLORER_RECORD              32961
#define ID_SF2_TOOL_1                   32962
#define ID_SF2_TOOL_2                   32963
#define ID_Menu                         32964
#define ID_VIEW_SOUND_FONT_2            32965
#define ID_VIEW_SF2TOOLBAR              32966
#define ID_VIEW_IE                      32967
#define ID_VIEW_IE_TOOLBAR              32968
#define ID_Menu32969                    32969
#define ID_EVENTS_INSERT_SUB            32970
#define ID_EVENTS_INSERT_BEFORE         32971
#define ID_EVENTS_INSERT_AFTER          32973
#define ID_EVENTS_REMIVE                32974
#define ID_EVENTS_REMOVE                32975

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32976
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           228
#endif
#endif
